### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by patademahesh** [grafov/streamsurfer#1]
Hey,

When i am trying to install streamsurfer, getting below mentioned error.

[root@config_server streamsurfer]# make install
make: *** No rule to make target `analyzer.go', needed by `streamsurfer'.  Stop.

Thanks in advance.

**Comment by joelkorpi** [comment]
I have the same problem:
go build -ldflags "-X main.build_date `date -u +%Y%m%d%H%M%S`" streamsurfer.go structure.go config.go monitor.go monitor-prober.go http-client.go http-api.go stats.go logger.go zabbix.go helpers.go helpers-md5.go templates.go webui-report.go analyzer.go db.go 
db.go:8:2: cannot find package "github.com/garyburd/redigo/redis" in any of:
	/usr/local/go/src/github.com/garyburd/redigo/redis (from $GOROOT)
	/home/axel/go/src/github.com/garyburd/redigo/redis (from $GOPATH)
http-api.go:9:2: cannot find package "github.com/gorilla/mux" in any of:
	/usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
	/home/axel/go/src/github.com/gorilla/mux (from $GOPATH)
monitor.go:7:2: cannot find package "github.com/grafov/bcast" in any of:
	/usr/local/go/src/github.com/grafov/bcast (from $GOROOT)
	/home/axel/go/src/github.com/grafov/bcast (from $GOPATH)
structure.go:7:2: cannot find package "github.com/grafov/m3u8" in any of:
	/usr/local/go/src/github.com/grafov/m3u8 (from $GOROOT)
	/home/axel/go/src/github.com/grafov/m3u8 (from $GOPATH)
config.go:9:2: cannot find package "launchpad.net/goyaml" in any of:
	/usr/local/go/src/launchpad.net/goyaml (from $GOROOT)
	/home/axel/go/src/launchpad.net/goyaml (from $GOPATH)
make: *** [streamsurfer] Error 1

**Comment by grafov** [comment]
@joelkorpi you just need to install dependencies first.

    go get github.com/garyburd/redigo/redis
    go get launchpad.net/goyaml
    go get github.com/grafov/m3u8 
    go get github.com/gorilla/mux
    go get github.com/grafov/bcast

and sorry but code unsupported now as I still not have time to continiue development.
